### Dataframe à partir d'un fichier csv

In [16]:
# Importer la bibliothèque pandas avec l'alias pd
import pandas as pd

In [17]:
df = pd.read_csv(r'C:\Users\HP\Documents\Feryel\TPDataMinning\Data_Analysis-main\Data_Analysis-main\TP1\notebooks\Affairs.csv',index_col=0)
df


affairs  gender   age  yearsmarried children  religiousness  education  \
4           0    male  37.0         10.00       no              3         18   
5           0  female  27.0          4.00       no              4         14   
11          0  female  32.0         15.00      yes              1         12   
16          0    male  57.0         15.00      yes              5         18   
23          0    male  22.0          0.75       no              2         17   
...       ...     ...   ...           ...      ...            ...        ...   
1938        1    male  22.0          1.50      yes              1         12   
1941        7  female  32.0         10.00      yes              2         18   
1954        2    male  32.0         10.00      yes              2         17   
1959        2    male  22.0          7.00      yes              3         18   
9010        1  female  32.0         15.00      yes              3         14   

      occupation  rating  
4              7       4  
5              6       4  
11             1       4  
16             6       5  
23             6       3  
...          ...     ...  
1938           2       5  
1941           5       4  
1954           6       5  
1959           6       2  
9010           1       5  

[601 rows x 9 columns]

In [18]:
df = pd.read_csv(r'C:\Users\HP\Documents\Feryel\TPDataMinning\Data_Analysis-main\Data_Analysis-main\TP1\notebooks\Affairs.csv')
df

Unnamed: 0  affairs  gender   age  yearsmarried children  religiousness  \
0             4        0    male  37.0         10.00       no              3   
1             5        0  female  27.0          4.00       no              4   
2            11        0  female  32.0         15.00      yes              1   
3            16        0    male  57.0         15.00      yes              5   
4            23        0    male  22.0          0.75       no              2   
..          ...      ...     ...   ...           ...      ...            ...   
596        1938        1    male  22.0          1.50      yes              1   
597        1941        7  female  32.0         10.00      yes              2   
598        1954        2    male  32.0         10.00      yes              2   
599        1959        2    male  22.0          7.00      yes              3   
600        9010        1  female  32.0         15.00      yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 10 columns]

In [19]:
### DataFrame à partir d'un fichier json

In [20]:
df.to_json('Affairs.json')

In [21]:
df = pd.read_json('Affairs.json')

df

Unnamed: 0  affairs  gender   age  yearsmarried children  religiousness  \
0             4        0    male  37.0         10.00       no              3   
1             5        0  female  27.0          4.00       no              4   
2            11        0  female  32.0         15.00      yes              1   
3            16        0    male  57.0         15.00      yes              5   
4            23        0    male  22.0          0.75       no              2   
..          ...      ...     ...   ...           ...      ...            ...   
596        1938        1    male  22.0          1.50      yes              1   
597        1941        7  female  32.0         10.00      yes              2   
598        1954        2    male  32.0         10.00      yes              2   
599        1959        2    male  22.0          7.00      yes              3   
600        9010        1  female  32.0         15.00      yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 10 columns]

In [22]:
DF=df.transpose()
DF

0       1       2     3     4       5       6     7       8    \
Unnamed: 0        4       5      11    16    23      29      44    45      47   
affairs           0       0       0     0     0       0       0     0       0   
gender         male  female  female  male  male  female  female  male  female   
age            37.0    27.0    32.0  57.0  22.0    32.0    22.0  57.0    32.0   
yearsmarried   10.0     4.0    15.0  15.0  0.75     1.5    0.75  15.0    15.0   
children         no      no     yes   yes    no      no      no   yes     yes   
religiousness     3       4       1     5     2       2       2     2       4   
education        18      14      12    18    17      17      12    14      16   
occupation        7       6       1     6     6       5       1     4       1   
rating            4       4       4     5     3       5       3     4       2   

                9    ...   591     592   593   594   595   596     597   598  \
Unnamed: 0       49  ...  1844    1856  1876  1929  1935  1938    1941  1954   
affairs           0  ...    12       7    12     3     7     1       7     2   
gender         male  ...  male  female  male  male  male  male  female  male   
age            22.0  ...  42.0    42.0  27.0  32.0  47.0  22.0    32.0  32.0   
yearsmarried    1.5  ...  15.0    15.0   7.0  10.0  15.0   1.5    10.0  10.0   
children         no  ...   yes     yes   yes   yes   yes   yes     yes   yes   
religiousness     4  ...     3       2     2     4     3     1       2     2   
education        14  ...    18      14    17    14    16    12      18    17   
occupation        4  ...     6       3     5     4     4     2       5     6   
rating            5  ...     2       2     4     3     2     5       4     5   

                599     600  
Unnamed: 0     1959    9010  
affairs           2       1  
gender         male  female  
age            22.0    32.0  
yearsmarried    7.0    15.0  
children        yes     yes  
religiousness     3       3  
education        18      14  
occupation        6       1  
rating            2       5  

[10 rows x 601 columns]

In [23]:
df.transpose().to_json('Affairs.json')

### Base de donné à partir d'un dataframe

Nous allons créer un fichier de base de donnée à partir du data frame **DF**



'<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Unamed</th>      <th>affairs</th> <th>gender</th> <th>age</th> <th>yearsmarried</th> <th>children</th> <th>religiousness</th> <th>education</th>  <th>occupation</th> <th>rating</th>  </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>4</td>      <td>0</td>  <td>male</td> <td>37.0</td>  <td>10.0</td> <td>no</td>  <td>3</td> <td>18</td> <td>7</td> <td>4</td></tr>    <tr>      <th>1</th>   <td>5</td>    <td>0</td>      <td>female</td>   <td>27.0</td>   <td>4.0</td> <td>no</td> <td>4</td> <td>14</td> <td>6</td> <td>4</td>   </tr>    <tr>      <th>2</th>      <td>11</td>      <td>0</td>   <td>female </td><td>32.0</td> <td>15.0</td><td>yes</td><td>1</td><td>12</td><td>1</td><td>4</td> </tr>    <tr>      <th>3</th>      <td>16</td>      <td>0</td>  <td>male</td> <td>57.0</td>  <td>15.0</td>  <td>yes</td>  <td>5</td>  <td>18</td>  <td>6</td>  <td>5</td>   </tr>  <th>4</th>      <td>23</td>      <td>0</td>  <td>male</td> <td>22.0</td>  <td>0.75</td> <td>no</td> <td>2</td> <td>17</td> <td>6</td> <td>3</td></tr>   </tr></tbody></table>'


### Création du contexte

In [93]:
import sqlite3
connection = sqlite3.connect('db.sqlite')
cursor = connection.cursor()
cursor.execute('Create Table if not exists Affairs (id Text, Unamed Integer, Affairs Integer, Gender String, Age Float, Yearsmarried Float, Children String, Religiousness Integer, Education Integer, Occupation Integer, Rating Integer)')
connection.commit()

#### Ingestion du dataframe Df dans la base de donnée

In [94]:
DF.to_sql('Affairs', connection, if_exists='replace', index = True)
connection.close()

In [95]:
con2=sqlite3.connect('db.sqlite')

In [96]:
df2 = pd.read_sql_query("SELECT * FROM Affairs", con2)

df2

index     0       1       2     3     4       5       6     7  \
0     Unnamed: 0     4       5      11    16    23      29      44    45   
1        affairs     0       0       0     0     0       0       0     0   
2         gender  male  female  female  male  male  female  female  male   
3            age  37.0    27.0    32.0  57.0  22.0    32.0    22.0  57.0   
4   yearsmarried  10.0     4.0    15.0  15.0  0.75     1.5    0.75  15.0   
5       children    no      no     yes   yes    no      no      no   yes   
6  religiousness     3       4       1     5     2       2       2     2   
7      education    18      14      12    18    17      17      12    14   
8     occupation     7       6       1     6     6       5       1     4   
9         rating     4       4       4     5     3       5       3     4   

        8  ...   591     592   593   594   595   596     597   598   599  \
0      47  ...  1844    1856  1876  1929  1935  1938    1941  1954  1959   
1       0  ...    12       7    12     3     7     1       7     2     2   
2  female  ...  male  female  male  male  male  male  female  male  male   
3    32.0  ...  42.0    42.0  27.0  32.0  47.0  22.0    32.0  32.0  22.0   
4    15.0  ...  15.0    15.0   7.0  10.0  15.0   1.5    10.0  10.0   7.0   
5     yes  ...   yes     yes   yes   yes   yes   yes     yes   yes   yes   
6       4  ...     3       2     2     4     3     1       2     2     3   
7      16  ...    18      14    17    14    16    12      18    17    18   
8       1  ...     6       3     5     4     4     2       5     6     6   
9       2  ...     2       2     4     3     2     5       4     5     2   

      600  
0    9010  
1       1  
2  female  
3    32.0  
4    15.0  
5     yes  
6       3  
7      14  
8       1  
9       5  

[10 rows x 602 columns]

### Importer une database en dataframe

In [97]:
con = sqlite3.connect("db.sqlite")

* Explorer les tables de la base de donnée 

In [98]:
cursor = con.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('purshases',), ('Affairs',)]


In [99]:
df = pd.read_sql_query("SELECT * FROM Affairs ", con)
df

index     0       1       2     3     4       5       6     7  \
0     Unnamed: 0     4       5      11    16    23      29      44    45   
1        affairs     0       0       0     0     0       0       0     0   
2         gender  male  female  female  male  male  female  female  male   
3            age  37.0    27.0    32.0  57.0  22.0    32.0    22.0  57.0   
4   yearsmarried  10.0     4.0    15.0  15.0  0.75     1.5    0.75  15.0   
5       children    no      no     yes   yes    no      no      no   yes   
6  religiousness     3       4       1     5     2       2       2     2   
7      education    18      14      12    18    17      17      12    14   
8     occupation     7       6       1     6     6       5       1     4   
9         rating     4       4       4     5     3       5       3     4   

        8  ...   591     592   593   594   595   596     597   598   599  \
0      47  ...  1844    1856  1876  1929  1935  1938    1941  1954  1959   
1       0  ...    12       7    12     3     7     1       7     2     2   
2  female  ...  male  female  male  male  male  male  female  male  male   
3    32.0  ...  42.0    42.0  27.0  32.0  47.0  22.0    32.0  32.0  22.0   
4    15.0  ...  15.0    15.0   7.0  10.0  15.0   1.5    10.0  10.0   7.0   
5     yes  ...   yes     yes   yes   yes   yes   yes     yes   yes   yes   
6       4  ...     3       2     2     4     3     1       2     2     3   
7      16  ...    18      14    17    14    16    12      18    17    18   
8       1  ...     6       3     5     4     4     2       5     6     6   
9       2  ...     2       2     4     3     2     5       4     5     2   

      600  
0    9010  
1       1  
2  female  
3    32.0  
4    15.0  
5     yes  
6       3  
7      14  
8       1  
9       5  

[10 rows x 602 columns]

In [ ]:
Pour enrejistrer un dataframe en format ```csv```

In [101]:
df.to_csv('new_affairs.csv')

## From CSV to DataFrame

- Dans cette partie nous allons:
    * Explorer le fichier CSV **`Affairs.csv`**
    * Voir l'utilité des méthodes `.head()` , `tail()`,`.info()`, `.shape`, `.append()`, ...
    * Appliquer quelques transformations au dataframe
    * Calculer quelques informations statistiques
 
 
 Essayer de décrire l'utilité de chaque opération et transformation :



In [102]:
affairs_df = pd.read_csv("../data/sources/Affairs.txt")

In [103]:
affairs_df.head()

Unnamed: 0  affairs  gender   age  yearsmarried children  religiousness  \
0           4        0    male  37.0         10.00       no              3   
1           5        0  female  27.0          4.00       no              4   
2          11        0  female  32.0         15.00      yes              1   
3          16        0    male  57.0         15.00      yes              5   
4          23        0    male  22.0          0.75       no              2   

   education  occupation  rating  
0         18           7       4  
1         14           6       4  
2         12           1       4  
3         18           6       5  
4         17           6       3

In [104]:
affairs_df.tail(2)

Unnamed: 0  affairs  gender   age  yearsmarried children  religiousness  \
599        1959        2    male  22.0           7.0      yes              3   
600        9010        1  female  32.0          15.0      yes              3   

     education  occupation  rating  
599         18           6       2  
600         14           1       5

In [105]:
affairs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     601 non-null    int64  
 1   affairs        601 non-null    int64  
 2   gender         601 non-null    object 
 3   age            601 non-null    float64
 4   yearsmarried   601 non-null    float64
 5   children       601 non-null    object 
 6   religiousness  601 non-null    int64  
 7   education      601 non-null    int64  
 8   occupation     601 non-null    int64  
 9   rating         601 non-null    int64  
dtypes: float64(2), int64(6), object(2)
memory usage: 47.1+ KB


In [106]:
affairs_df.shape

(601, 10)

In [107]:
temp_df = affairs_df.append(affairs_df)

temp_df.shape

C:\Users\HP\AppData\Local\Temp\ipykernel_19800\306393328.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  temp_df = affairs_df.append(affairs_df)


(1202, 10)

In [108]:
temp_df.drop_duplicates(inplace=True)

In [109]:
temp_df = affairs_df.append(affairs_df)  # make a new copy

temp_df.drop_duplicates(inplace=True, keep=False)

temp_df.shape

C:\Users\HP\AppData\Local\Temp\ipykernel_19800\267359950.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  temp_df = affairs_df.append(affairs_df)  # make a new copy


(0, 10)

In [110]:
affairs_df.columns

Index(['Unnamed: 0', 'affairs', 'gender', 'age', 'yearsmarried', 'children',
       'religiousness', 'education', 'occupation', 'rating'],
      dtype='object')

In [112]:
affairs_df.rename(columns={
        'affairs': 'Affairs', 
        'gender': 'Gender',
        'age': 'Age',
        'yearsmarried': 'Years_married',
        'children': 'Children',
        'religiousness': 'Religiousness',
         'education':  'Education',
        'occupation': 'Occupation',
        'rating': 'Rating'
    }, inplace=True)


affairs_df.columns

Index(['Unnamed: 0', 'Affairs', 'Gender', 'Age', 'Years_married', 'Children',
       'Religiousness', 'Education', 'Occupation', 'Rating'],
      dtype='object')

In [113]:
affairs_df.columns = ['Unamed', 'affairs', 'gender', 'age', 'yearsmarried', 'children', 'religiousness', 
                     'education', 'occupation', 'rating']


affairs_df.columns

Index(['Unamed', 'affairs', 'gender', 'age', 'yearsmarried', 'children',
       'religiousness', 'education', 'occupation', 'rating'],
      dtype='object')

In [114]:
affairs_df.columns = [col.lower() for col in affairs_df]

affairs_df.columns

Index(['unamed', 'affairs', 'gender', 'age', 'yearsmarried', 'children',
       'religiousness', 'education', 'occupation', 'rating'],
      dtype='object')

In [115]:
affairs_df.isnull()

unamed  affairs  gender    age  yearsmarried  children  religiousness  \
0     False    False   False  False         False     False          False   
1     False    False   False  False         False     False          False   
2     False    False   False  False         False     False          False   
3     False    False   False  False         False     False          False   
4     False    False   False  False         False     False          False   
..      ...      ...     ...    ...           ...       ...            ...   
596   False    False   False  False         False     False          False   
597   False    False   False  False         False     False          False   
598   False    False   False  False         False     False          False   
599   False    False   False  False         False     False          False   
600   False    False   False  False         False     False          False   

     education  occupation  rating  
0        False       False   False  
1        False       False   False  
2        False       False   False  
3        False       False   False  
4        False       False   False  
..         ...         ...     ...  
596      False       False   False  
597      False       False   False  
598      False       False   False  
599      False       False   False  
600      False       False   False  

[601 rows x 10 columns]

In [116]:
affairs_df.isnull().sum()

unamed           0
affairs          0
gender           0
age              0
yearsmarried     0
children         0
religiousness    0
education        0
occupation       0
rating           0
dtype: int64

In [117]:
affairs_df.dropna()

unamed  affairs  gender   age  yearsmarried children  religiousness  \
0         4        0    male  37.0         10.00       no              3   
1         5        0  female  27.0          4.00       no              4   
2        11        0  female  32.0         15.00      yes              1   
3        16        0    male  57.0         15.00      yes              5   
4        23        0    male  22.0          0.75       no              2   
..      ...      ...     ...   ...           ...      ...            ...   
596    1938        1    male  22.0          1.50      yes              1   
597    1941        7  female  32.0         10.00      yes              2   
598    1954        2    male  32.0         10.00      yes              2   
599    1959        2    male  22.0          7.00      yes              3   
600    9010        1  female  32.0         15.00      yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 10 columns]

In [118]:
affairs_df.dropna(axis=1)

unamed  affairs  gender   age  yearsmarried children  religiousness  \
0         4        0    male  37.0         10.00       no              3   
1         5        0  female  27.0          4.00       no              4   
2        11        0  female  32.0         15.00      yes              1   
3        16        0    male  57.0         15.00      yes              5   
4        23        0    male  22.0          0.75       no              2   
..      ...      ...     ...   ...           ...      ...            ...   
596    1938        1    male  22.0          1.50      yes              1   
597    1941        7  female  32.0         10.00      yes              2   
598    1954        2    male  32.0         10.00      yes              2   
599    1959        2    male  22.0          7.00      yes              3   
600    9010        1  female  32.0         15.00      yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 10 columns]

In [124]:
age = affairs_df['age']

In [125]:
age.head()

0    37.0
1    27.0
2    32.0
3    57.0
4    22.0
Name: age, dtype: float64

In [127]:
age_mean = age.mean()

age_mean

32.48752079866888

In [128]:
age.fillna(age_mean, inplace=True)

In [129]:
affairs_df.isnull().sum()

unamed           0
affairs          0
gender           0
age              0
yearsmarried     0
children         0
religiousness    0
education        0
occupation       0
rating           0
dtype: int64

In [130]:
affairs_df.describe()

unamed     affairs         age  yearsmarried  religiousness  \
count   601.000000  601.000000  601.000000    601.000000     601.000000   
mean   1059.722130    1.455907   32.487521      8.177696       3.116473   
std     914.904611    3.298758    9.288762      5.571303       1.167509   
min       4.000000    0.000000   17.500000      0.125000       1.000000   
25%     528.000000    0.000000   27.000000      4.000000       2.000000   
50%    1009.000000    0.000000   32.000000      7.000000       3.000000   
75%    1453.000000    0.000000   37.000000     15.000000       4.000000   
max    9029.000000   12.000000   57.000000     15.000000       5.000000   

        education  occupation      rating  
count  601.000000  601.000000  601.000000  
mean    16.166389    4.194676    3.931780  
std      2.402555    1.819443    1.103179  
min      9.000000    1.000000    1.000000  
25%     14.000000    3.000000    3.000000  
50%     16.000000    5.000000    4.000000  
75%     18.000000    6.000000    5.000000  
max     20.000000    7.000000    5.000000

In [131]:
affairs_df.sort_values(by='unamed')

unamed  affairs  gender   age  yearsmarried children  religiousness  \
0         4        0    male  37.0          10.0       no              3   
1         5        0  female  27.0           4.0       no              4   
451       6        3    male  27.0           1.5       no              3   
2        11        0  female  32.0          15.0      yes              1   
452      12        3  female  27.0           4.0      yes              3   
..      ...      ...     ...   ...           ...      ...            ...   
447    9001        0    male  47.0          15.0       no              4   
600    9010        1  female  32.0          15.0      yes              3   
448    9012        0    male  37.0          10.0      yes              2   
449    9023        0    male  37.0          15.0      yes              3   
450    9029        0  female  27.0           4.0      yes              2   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
451         18           4       4  
2           12           1       4  
452         17           1       5  
..         ...         ...     ...  
447         14           5       4  
600         14           1       5  
448         18           6       2  
449         17           5       4  
450         16           1       4  

[601 rows x 10 columns]

In [132]:
affairs_df.sort_index(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_19800\1050614.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  affairs_df.sort_index(1)


affairs   age children  education  gender  occupation  rating  \
0          0  37.0       no         18    male           7       4   
1          0  27.0       no         14  female           6       4   
2          0  32.0      yes         12  female           1       4   
3          0  57.0      yes         18    male           6       5   
4          0  22.0       no         17    male           6       3   
..       ...   ...      ...        ...     ...         ...     ...   
596        1  22.0      yes         12    male           2       5   
597        7  32.0      yes         18  female           5       4   
598        2  32.0      yes         17    male           6       5   
599        2  22.0      yes         18    male           6       2   
600        1  32.0      yes         14  female           1       5   

     religiousness  unamed  yearsmarried  
0                3       4         10.00  
1                4       5          4.00  
2                1      11         15.00  
3                5      16         15.00  
4                2      23          0.75  
..             ...     ...           ...  
596              1    1938          1.50  
597              2    1941         10.00  
598              2    1954         10.00  
599              3    1959          7.00  
600              3    9010         15.00  

[601 rows x 10 columns]